### ISSUE TITLE
regex to check emails can be added

### ISSUE THREAD

**Issue by ninjatrench** [icanhasfay/PyPwned#1]
Simple regex check to verify the email address before making http request to api.

example code inside function getAllBreachesForAccount
on line number 18 :---

import re
pattern = re.compile(r"[^@]+@[^@]+.[^@]+")
if not pattern.match(email):
    return fourHundredString

**Comment by icanhasfay** [comment]
Sorry about taking so long to add that, slipped my mind :(
The referenced commit should do the trick.
