### ISSUE TITLE
getAllBreachesForAccount() fails with JSONDecodeError when rate limit is exceeded

### ISSUE THREAD

**Issue by RevolutionTech** [icanhasfay/PyPwned#2]
The status code 429 is not handled by the client, so it falls into the `r.json()` else clause, resulting in a JSONDecodeError, since the response content is simply the string: "Rate limit exceeded, refer to acceptable use of API: https://haveibeenpwned.com/API/v2#AcceptableUse".

**Comment by icanhasfay** [comment]
Hey @RevolutionTech, just committed a fix for handling 429's. Also pushed it to pypi. Appreciate the spot! Feel free to reopen if you feel the fix is insufficient.

**Comment by RevolutionTech** [comment]
Wow, thanks for the quick turnaround!
