### ISSUE TITLE
requests is used but not in install_requires

### ISSUE THREAD

**Issue by RevolutionTech** [icanhasfay/PyPwned#3]
The Python package `requests` is not declared in `install_requires` in `setup.py`, but it is used by the library.

This wouldn't be an issue for most users as virtually all Python users have `requests` installed already, but if a user didn't have `requests` installed, they would run into an `ImportError`.

https://packaging.python.org/requirements/#install-requires

(I ran into this issue when installing PyPwned on a fresh EC2 instance).

**Comment by icanhasfay** [comment]
Thanks for the info @RevolutionTech. Just pushed out a fix that looks like it solves the issue. I was doing some odd references in the setup.py file that I changed. Looks like it should install requests fine now. Let me know if you find otherwise.

-Eric

**Comment by RevolutionTech** [comment]
Thanks so much!
