### ISSUE TITLE
403 - Forbidden - no user agent has been specified in the request

### ISSUE THREAD

**Issue by doritoes** [icanhasfay/PyPwned#8]
Provided sample code did not work.

> pip install pypwned

> vi p.py
import pypwned
print pypwned.getAllBreachesForAccount(email="foo@bar.com")

> python p.py
403 - Forbidden - no user agent has been specified in the request

On the other hand, the following works:
> import pypwned
print pypwned.getAllPastesForAccount(account="foo@bar.com")

**Comment by icanhasfay** [comment]
Hey @doritoes thanks for pointing this out and I apologize for the delay in resolving. Unfortunately it looks like it was a very minor change in the HIBP api that seemed to cause the issue, see the reference commit above.

I just pushed the new version to PyPi and tested your case, which seems to work again. Feel free to reach out over Twitter if i'm taking too long (https://twitter.com/icanhasfay) and thanks again!
